### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gabriel-maxx** [BugFor-Pings/CobaltStrike4.8#1]
┌──(kali㉿kali)-[~/Downloads/CobaltStrike4.8/Server]
└─$ sudo bash teamserver 192.168.1.15 test123

[*] Will use existing X509 certificate and keystore (for SSL)

[*] Starting teamserver
teamserver: line 47: ./TeamServerImage: cannot execute binary file: Exec format error
                                                                             
┌──(kali㉿kali)-[~/Downloads/CobaltStrike4.8/Server]
└─$

**Comment by g0dxing** [comment]
uname -a查看一下是否是64位的机器，可能机器不是64位的
